use_frameworks!

platform :ios, '10.0'

target 'JXNetwork_Example' do
  pod 'JXNetwork', :path => '../'

  target 'JXNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
